[tool.poetry]
name = "ytapi-dynamodb"
version = "0.1.0"
description = ""
authors = ["Christian Reil <christian.reil@lhind.dlh.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pydantic = "^2.4.2"
aws-lambda-powertools = "^2.26.1"
requests = "^2.31.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
