name: Test&Deploy

on: push

env:
  AWS_DEFAULT_REGION: eu-central-1

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
          version: 1.6.1
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'poetry'
      - name: Install Dependencies
        run:
          poetry install --no-interaction --no-root --no-ansi
      - name: Run tests
        run: |
          source .venv/bin/activate
          export PYTHONPATH=$(pwd)/functions
          pytest -c tests/pytest.ini

  deploy:
    needs: [ test ]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform

    steps:
      - uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false
          terraform_version: 1.2.2
      - name: Terraform Init, Plan & Apply
        id: terraform
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_YT_API_KEY: ${{ secrets.YT_API_KEY }}
          AWS_REGION: eu-central-1
        run: |
          terraform init
          terraform plan -no-color
          terraform apply -auto-approve